---
language: ruby
before_script: 'bundle exec rake fixture:prepare'
script: 'SPEC_OPTS="--format documentation" bundle exec rake spec'
notifications:
  email: false
rvm:
  - 1.9.3
  - 1.8.7
env:
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.0
